### ISSUE TITLE
Enable Language Processing

### ISSUE THREAD

**Issue by simsays** [hmc-cs-sfriedrich/Shakespeare#4]
As a developer, I want to be able to analyze the text from the XML file using other libraries (e.g. syllable count) so that we can provide the analysis to our users.

**Comment by robertmlinden** [comment]
Hey Simon, in the typical user story format, you should add a "so that" so we know why we're doing something. Also, can you be more specific about what this means? You can do so in a comment below. It's just that we talked a lot about xml files, so it seemed like "computing" could go a bunch of different ways.

**Comment by simsays** [comment]
Done.

**Comment by robertmlinden** [comment]
This card has a HUGE scope. At some point, I would suggest that you break this up into the individual features (syllable count, consonant dimming, etc.)

**Comment by robertmlinden** [comment]
Too broad in scope
